name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
        
    - name: Extract tag from release
      run: echo "RELEASE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ steps.extract_version.outputs.VERSION }}
          build-args: |
            VERSION=${{ steps.extract_version.outputs.VERSION }}

